name: Update Trophies

on:
  schedule:
    - cron: '0 0 * * *' # Каждый день в полночь
  workflow_dispatch: # Чтобы запустить вручную

permissions:
  contents: write # Разрешает экшену записывать файлы в репозиторий

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Generate Trophies
        uses: ryo-ma/github-profile-trophy@master
        with:
          username: vokrob
          theme: matrix
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Commit and Push
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          # Принудительно перезаписываем старый битый файл, если он изменился
          git add trophy.svg
          git commit -m "Update trophies" || echo "No changes to commit"
          git push origin main
